abc:
  outputs:
    dev:
      dbname: companyxdb
      host: localhost
      pass: P@ssW0rd
      port: 55432
      schema: gold
      threads: 1
      type: postgres
      user: companyx
  target: dev
