version: 2

models:
  - name: dim_date
    description: "Date dimension for time-based analysis."
    columns:
      - name: date_sk
        description: "Surrogate key for date."
        tests:
          - unique
          - not_null
      - name: date
        description: "The date."
        tests:
          - not_null
      - name: year
        description: "Year of the date."
      - name: month
        description: "Month of the date."
      - name: day
        description: "Day of the date."

  - name: dim_customer
    description: "Customer dimension with personal and territory details."
    columns:
      - name: customer_sk
        description: "Surrogate key for customer."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Business key for customer."
        tests:
          - not_null
      - name: business_entity_id
        description: "Person business entity ID."
      - name: first_name
        description: "Customer first name."
      - name: last_name
        description: "Customer last name."
      - name: email_address
        description: "Customer email."
      - name: territory_name
        description: "Sales territory name."
      - name: address_line1
        description: "Address line 1."