version: 2

models:
  - name: dim_date
    description: "Date dimension for time-based analysis."
    columns:
      - name: date_sk
        description: "Surrogate key for date."
        tests:
          - unique
          - not_null
      - name: date
        description: "The date."
        tests:
          - not_null
      - name: year
        description: "Year of the date."
      - name: month
        description: "Month of the date."
      - name: day
        description: "Day of the date."

  - name: dim_customer
    description: "Customer dimension with personal and territory details."
    columns:
      - name: customer_sk
        description: "Surrogate key for customer."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Business key for customer."
        tests:
          - not_null
      - name: business_entity_id
        description: "Person business entity ID."
      - name: first_name
        description: "Customer first name."
      - name: last_name
        description: "Customer last name."
      - name: email_address
        description: "Customer email."
      - name: territory_name
        description: "Sales territory name."
      - name: address_line1
        description: "Address line 1."

  - name: dim_product
    description: "Product dimension with category details."
    columns:
      - name: product_sk
        description: "Surrogate key for product."
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Business key for product."
        tests:
          - not_null
      - name: product_name
        description: "Product name."
      - name: color
        description: "Product color."
      - name: list_price
        description: "List price."
      - name: subcategory_name
        description: "Product subcategory name."
      - name: category_name
        description: "Product category name."

  - name: dim_territory
    description: "Territory dimension."
    columns:
      - name: territory_sk
        description: "Surrogate key for territory."
        tests:
          - unique
          - not_null
      - name: territory_id
        description: "Business key for territory."
        tests:
          - not_null
      - name: territory_name
        description: "Territory name."
      - name: country_region_code
        description: "Country region code."
      - name: territory_group
        description: "Territory group."

  - name: dim_address
    description: "Address dimension."
    columns:
      - name: address_sk
        description: "Surrogate key for address."
        tests:
          - unique
          - not_null
      - name: address_id
        description: "Business key for address."
        tests:
          - not_null
      - name: address_line1
        description: "Address line 1."
      - name: city
        description: "City."
      - name: postal_code
        description: "Postal code."