version: 2

models:
  - name: fact_sales_order_line
    description: "Fact table for sales order lines."
    columns:
      - name: sales_order_line_sk
        description: "Surrogate key for order line."
        tests:
          - unique
          - not_null
      - name: salesorder_sk
        description: "Surrogate key for sales order."
      - name: product_sk
        description: "Surrogate key for product."
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_sk
      - name: customer_sk
        description: "Surrogate key for customer."
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_sk
      - name: territory_sk
        description: "Surrogate key for territory."
        tests:
          - relationships:
              arguments:
                to: ref('dim_territory')
                field: territory_sk
      - name: order_date_sk
        description: "Surrogate key for order date."
        tests:
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_sk
      - name: order_qty
        description: "Order quantity."
      - name: unit_price
        description: "Unit price."
      - name: line_total
        description: "Line total."
        tests:
          - not_null