version: 2

models:
  - name: fact_sales_order_line
    description: "Fact table for sales order lines."
    columns:
      - name: sales_order_line_sk
        description: "Surrogate key for order line."
        tests:
          - unique
          - not_null
      - name: order_qty
        description: "Order quantity."
      - name: unit_price
        description: "Unit price."
      - name: line_total
        description: "Line total."
        tests:
          - not_null
  - name: fact_customer_churn
